# Generated by Django 3.1 on 2021-06-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desease', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desease_name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'desease',
                'verbose_name_plural': 'deseases',
            },
        ),
        migrations.DeleteModel(
            name='Symptom',
        ),
    ]
