# Generated by Django 3.1 on 2021-07-06 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0004_remove_symptom_desease_name'),
        ('desease', '0003_auto_20210706_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='desease',
            name='symptom_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='symptoms.symptom'),
        ),
        migrations.AlterField(
            model_name='desease',
            name='desease_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
