# Generated by Django 3.1 on 2021-07-05 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0003_auto_20210628_0600'),
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='symptom_name',
        ),
        migrations.CreateModel(
            name='CaseSymptoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.case')),
                ('symptom_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='symptoms.symptom')),
            ],
        ),
    ]
