# Generated by Django 3.1 on 2021-07-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_auto_20210705_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='desease_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
