# Generated by Django 3.1 on 2021-06-28 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desease', '0002_auto_20210628_0559'),
        ('symptoms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptom',
            name='Symname',
        ),
        migrations.AddField(
            model_name='symptom',
            name='Symptom_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='symptom',
            name='desease_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='desease.desease'),
        ),
    ]
