# Generated by Django 3.1 on 2021-06-28 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0002_auto_20210628_0559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='symptom',
            old_name='Symptom_name',
            new_name='symptom_name',
        ),
    ]
